### ISSUE TITLE
Desktop: Better layout

### ISSUE THREAD

**Issue by umanghome** [flackr/crosswordle#7]
Currently, everything is stacked on top of each other, leading to a vertical scroll when there are a few clues.

![image](https://user-images.githubusercontent.com/5698706/151989852-04738957-b01e-45b7-b562-fa67ed1bfcd5.png)

Maybe we could lay the clues and the game blocks horizontally on Desktop?

![image](https://user-images.githubusercontent.com/5698706/151990156-83fbd197-365d-4d60-97ef-b54f1fefe27e.png)

CSS changes for this^ are on `.game`:

```css
.game {
    grid-area: game;
    justify-self: center;
    width: 100%;
    display: flex;
    align-items: start;
    justify-content: space-around;
    flex-flow: row-reverse;
}
```

but there'd be some responsive breakpoints needed too (or flex-wrap + min-width) for this to work on mobile.
